FROM node:8-alpine

ENV NODE_ENV development

RUN mkdir -p /opt/app/fake-balance-api

ADD package.json package-lock.json /opt/app/fake-balance-api/

WORKDIR /opt/app/fake-balance-api

RUN npm install

CMD ["npm", "start"]
